#:schema ./schema.json

id = "featbit-data-analytics"
name = "FeatBit Data Analytics Server"
icon = "https://icons.zeabur.com/featbit.png"
description = "FeatBit Data Analytics Server"

[source]
image = "featbit/featbit-data-analytics-server:latest"

[[ports]]
id = "web"
port = 80
type = "HTTP"

[env]
REDIS_HOST = { default = "${REDIS_HOST}" }
REDIS_PASSWORD = { default = "${REDIS_PASSWORD}" }
REDIS_PORT = { default = "${REDIS_PORT}" }
MONGO_URI = { default = "${MONGO_CONNECTION_STRING}" }
MONGO_INITDB_DATABASE = { default = "featbit" }
MONGO_HOST = { default = "mongodb.zeabur.internal" }
CHECK_DB_LIVNESS = { default = "true" }
