#:schema ./schema.json

id = "featbit-evaluation"
name = "FeatBit Evaluation Server"
icon = "https://icons.zeabur.com/featbit.png"
description = "FeatBit Evaluation Server"

[source]
image = "featbit/featbit-evaluation-server:latest"

[[ports]]
id = "web"
port = 5100
type = "HTTP"

[env]
MongoDb__ConnectionString = { default = "${MONGO_CONNECTION_STRING}" }
MongoDb__Database = { default = "featbit" }
Redis__ConnectionString = { default = "redis.zeabur.internal:6379,password=${REDIS_PASSWORD}" }
