#:schema ./schema.json

id = "featbit-api"
name = "FeatBit API Server"
icon = "https://icons.zeabur.com/featbit.png"
description = "FeatBit API Server"

[source]
image = "featbit/featbit-api-server:latest"

[[ports]]
id = "web"
port = 5000
type = "HTTP"

[env]
MongoDb__ConnectionString = { default = "${MONGO_CONNECTION_STRING}" }
MongoDb__Database = { default = "featbit" }
Redis__ConnectionString = { default = "redis.zeabur.internal:6379,password=${REDIS_PASSWORD}" }
OLAP__ServiceHost = { default = "http://featbit-data-analytics-server.zeabur.internal" }
