#:schema ./schema.json

id = "teable-migrate"
name = "Teable (Database Migrator)"
icon = "https://avatars.githubusercontent.com/u/113977713"
description = "One-shot utility for migrating the database. Deploy it before the main service."

[source]
image = "ghcr.io/teableio/teable-db-migrate:latest"

[env]
TZ = { default = "Asia/Shanghai" }
PRISMA_DATABASE_URL = { default = "${POSTGRES_CONNECTION_STRING}" }
